version: '3.8'

services:
  zellij-utils-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: zellij-utils-test
    environment:
      - TERM=xterm-256color
      - DEBIAN_FRONTEND=noninteractive
      - TEST_OUTPUT_DIR=/app/test-results
      - TEST_VERBOSE=true
      - ZJ_DEBUG_MODE=true
      - ZJ_DISABLE_AUTO=1
      - ZJ_TEST_MODE=1
      - ZELLIJ_CONFIG_DIR=/home/testuser/.config/zellij
    volumes:
      # Mount source code for development
      - ../:/app/zellij-utils:ro
      # Mount test results output
      - test-results:/app/test-results
      # Mount logs
      - test-logs:/app/logs
    working_dir: /app/zellij-utils
    command: /bin/bash -c "cleanup-sessions.sh && ./docker/run_tests.sh"
    # Keep container running for debugging
    tty: true
    stdin_open: true
    # Ensure complete session isolation
    pid: host
    privileged: false
    
  # Additional test environment for compatibility testing
  zellij-utils-test-alpine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.alpine
    container_name: zellij-utils-test-alpine
    environment:
      - TERM=xterm-256color
      - TEST_OUTPUT_DIR=/app/test-results
      - TEST_VERBOSE=true
      - ZJ_DISABLE_AUTO=1
      - ZJ_TEST_MODE=1
      - ZELLIJ_CONFIG_DIR=/home/testuser/.config/zellij
    volumes:
      - ../:/app/zellij-utils:ro
      - test-results-alpine:/app/test-results
    working_dir: /app/zellij-utils
    command: /bin/bash -c "cleanup-sessions.sh && ./docker/run_tests.sh"
    profiles:
      - alpine-test
    # Ensure complete session isolation
    pid: host
    privileged: false

volumes:
  test-results:
    driver: local
  test-logs:
    driver: local
  test-results-alpine:
    driver: local

networks:
  default:
    name: zellij-utils-test-network