name: Simple Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Zellij
      run: |
        ZELLIJ_VERSION="v0.42.2"
        curl -L "https://github.com/zellij-org/zellij/releases/download/${ZELLIJ_VERSION}/zellij-x86_64-unknown-linux-musl.tar.gz" -o /tmp/zellij.tar.gz
        tar -xzf /tmp/zellij.tar.gz -C /tmp
        sudo mv /tmp/zellij /usr/local/bin/
        chmod +x /usr/local/bin/zellij
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git bc curl wget
        
    - name: Set up test environment
      run: |
        mkdir -p ~/.config/zellij
        mkdir -p test-results
        export ZJ_DISABLE_AUTO=1
        export ZJ_TEST_MODE=1
        
    - name: Run basic tests
      run: |
        # Test 1: Check zellij installation
        zellij --version
        
        # Test 2: Source main script
        source scripts/zellij-utils.sh
        
        # Test 3: Check functions are loaded
        type zj >/dev/null && echo "✓ zj function loaded"
        type zjl >/dev/null && echo "✓ zjl function loaded"
        
        # Test 4: Test session creation (detached)
        timeout 30 zellij -d -s test-session
        
        # Test 5: List sessions
        zellij list-sessions | grep test-session && echo "✓ Session created"
        
        # Test 6: Kill session
        zellij kill-session test-session && echo "✓ Session killed"
        
        echo "All basic tests passed!"
        
    - name: Test installation script
      run: |
        # Test installation script syntax
        bash -n scripts/install.sh && echo "✓ Install script syntax OK"
        
    - name: Test config validation
      run: |
        source scripts/zellij-utils.sh
        # Test basic config validation if functions exist
        if type zj_validate_session_name >/dev/null 2>&1; then
          echo "✓ Config validation functions available"
        fi